language: java

jdk:
#  - oraclejdk8
  - oraclejdk7
#  - openjdk7

services:
  - mongodb

before_install:
 - chmod +x gradlew

install:
#  - TERM=dumb ./gradlew assemble

script:
  - TERM=dumb ./gradlew :test-server/core:check